# Step 1: Build the Go application
FROM golang:1.20 AS builder

WORKDIR /app

COPY seller-service .

RUN CGO_ENABLED=0 GOOS=linux go build -a -o seller-service  .

# Step 2: Create a lightweight container
FROM alpine:latest

RUN apk --no-cache add ca-certificates

WORKDIR /

# Copy the compiled binary from the builder stage
COPY --from=builder /app/seller-service .

# Expose the necessary ports (if any)
EXPOSE 8080

# Define the command to run the application
CMD ["./seller-service"]
