version: "3"

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - mynetwork

  app:
    build:
      context: .
      dockerfile: Dockerfile.seller
    volumes:
      - ./seller-service:/app
    ports:
      - "8080:8080"
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_PASSWORD: 'password'
      MYSQL_USER: 'user'
      MYSQL_HOSTNAME: 'db'
      MYSQL_PORT: '3306'
      MYSQL_PARAMETER: ''
      ENABLE_DEV_MODE: 'true'
    expose:
      - "3306"
      - "8080"
    depends_on:
      - db
    networks:
     - mynetwork


networks:
  mynetwork:
    external: true

volumes:
  my-db: